source 'https://rubygems.org'

gem 'activerecord-session_store', '>= 2.0.0'
gem 'ansi', '~> 1.5.0'
gem 'bootstrap', '~> 4.4.1'
gem 'coffee-rails', '>= 5.0.0'
gem 'countries', require: 'countries/global'
gem 'devise', '~> 4.7.2'
gem 'dotenv-rails', '>= 2.7.3'
gem 'font-awesome-rails', '>= 4.7.0.5'
gem 'httparty'
gem 'jbuilder'
gem 'jquery-rails', '>= 4.3.4'
gem 'mysql2', '~> 0.4.10'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.16.5'
gem 'omniauth'
gem 'omniauth-google-oauth2', '~> 0.6.0'
gem 'paper_trail'
gem 'paranoia'
gem 'puma'
gem 'rails', '5.1.7'
gem 'redis'
gem 'rotp'
gem 'rqrcode', '~> 0.10.1'
gem 'ruby-saml', '1.9.0'
gem 'saml_idp', git: 'https://github.com/gate-sso/saml_idp'
gem 'sass-rails', '>= 5.0.8'
gem 'sdoc', group: :doc
gem 'slim-rails', '>= 3.3.0'
gem 'turbolinks'
gem 'uglifier'
gem 'whenever', require: false

group :development, :test do
  gem 'capybara', '>= 3.13.0'
  gem 'coveralls', '>= 0.8.22'
  gem 'database_cleaner'
  gem 'dredd_hooks'
  gem 'factory_bot_rails', '>= 5.0.0'
  gem 'faker'
  gem 'mock_redis'
  gem 'pry'
  gem 'rails-controller-testing', '>= 1.0.5'
  gem 'rspec-rails', '>= 3.8.2'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
  gem 'simplecov', '>= 0.16.1'
  gem 'simplecov-console', '>= 0.4.2'
  gem 'timecop'
  gem 'webmock'
end

group :development do
  gem 'web-console', '>= 4.0.0', platform: :ruby
end
