source 'https://rubygems.org'

gem 'activerecord-session_store', '>= 1.1.3'
gem 'ansi', '~> 1.5.0'
gem 'bootstrap', '~> 4.3.1'
gem 'coffee-rails', '>= 4.2.2'
gem 'countries', require: 'countries/global'
gem 'devise', '~> 4.7.1'
gem 'dotenv-rails', '>= 2.7.2'
gem 'font-awesome-rails', '>= 4.7.0.4'
gem 'httparty'
gem 'jbuilder'
gem 'jquery-rails', '>= 4.3.3'
gem 'mysql2', '~> 0.4.10'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.10.8' 
gem 'omniauth'
gem 'omniauth-google-oauth2', '~> 0.6.0'
gem 'paper_trail'
gem 'paranoia'
gem 'puma', '>= 4.3.11'
gem 'rails', '5.2.6.2'
gem 'redis'
gem 'rotp'
gem 'rqrcode', '~> 0.10.1'
gem 'ruby-saml', '1.8.0'
gem 'saml_idp', git: 'https://github.com/gate-sso/saml_idp'
gem 'sass-rails', '>= 5.0.7'
gem 'sdoc', group: :doc
gem 'slim-rails', '>= 3.2.0'
gem 'turbolinks'
gem 'uglifier'
gem 'whenever', require: false

group :development, :test do
  gem 'capybara'
  gem 'coveralls'
  gem 'database_cleaner'
  gem 'dredd_hooks'
  gem 'factory_bot_rails', '>= 4.11.1'
  gem 'faker'
  gem 'mock_redis'
  gem 'pry'
  gem 'rails-controller-testing', '>= 1.0.4'
  gem 'rspec-rails', '>= 3.8.1'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'timecop'
  gem 'webmock'
end

group :development do
  gem 'web-console', '>= 3.7.0', platform: :ruby
end
