source 'https://rubygems.org'

gem 'activerecord-session_store'
gem 'ansi', '~> 1.5.0'
gem 'bootstrap', '~> 4.3.1'
gem 'coffee-rails'
gem 'countries', require: 'countries/global'
gem 'devise', '~> 4.7.1'
gem 'dotenv-rails', '>= 2.7.6'
gem 'font-awesome-rails', '>= 4.7.0.6'
gem 'httparty'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mysql2', '~> 0.4.10'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.10.8' 
gem 'omniauth'
gem 'omniauth-google-oauth2', '~> 0.6.0'
gem 'paper_trail', '>= 10.3.1'
gem 'paranoia', '>= 2.4.3'
gem 'puma'
gem 'rails', '6.1.7.3'
gem 'redis'
gem 'rotp'
gem 'rqrcode', '~> 0.10.1'
gem 'ruby-saml', '1.8.0'
gem 'saml_idp', git: 'https://github.com/gate-sso/saml_idp'
gem 'sass-rails', '>= 5.0.8'
gem 'sdoc', group: :doc
gem 'slim-rails'
gem 'turbolinks'
gem 'uglifier'
gem 'whenever', require: false

group :development, :test do
  gem 'capybara'
  gem 'coveralls', '>= 0.8.22'
  gem 'database_cleaner'
  gem 'dredd_hooks'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'mock_redis'
  gem 'pry'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
  gem 'simplecov', '>= 0.16.1'
  gem 'simplecov-console', '>= 0.4.2'
  gem 'timecop'
  gem 'webmock'
end

group :development do
  gem 'web-console', platform: :ruby
end
